/**
 * This file was auto-generated by openapi-typescript.
 * BioVoid OpenAPI SHA256: bc5eb01bd1f3f0e8248cc64373aafeb09c78d07131c3265943b6269906487fbe
 * Do not make direct changes to the file.
 */

export interface paths {
    "/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Artifacts
         * @description Report that local generated files are not served by the API.
         */
        get: operations["list_artifacts_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Atlas Overview */
        get: operations["atlas_overview_atlas_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/atlas/pockets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Atlas Pockets */
        get: operations["atlas_pockets_atlas_pockets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmark/fpocket-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fpocket Comparison
         * @description Load fpocket vs BioVoid comparison data.
         */
        get: operations["fpocket_comparison_benchmark_fpocket_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmark/known-pockets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Known Pockets
         * @description Return non-sensitive metadata for the historical development set.
         */
        get: operations["get_known_pockets_benchmark_known_pockets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/pockets.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Pockets Csv
         * @description Export run-scoped heuristic pocket observations as CSV.
         */
        get: operations["export_pockets_csv_export_pockets_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description List all jobs, optionally filtered by status.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Submit Job */
        post: operations["submit_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Batch */
        post: operations["submit_batch_jobs_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel a queued job.
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Job Result */
        get: operations["download_job_result_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/visualization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Visualization
         * @description Return Plotly-ready visualization data for a completed job.
         */
        get: operations["job_visualization_jobs__job_id__visualization_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ops/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops Metrics */
        get: operations["ops_metrics_ops_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protein/{pdb_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Protein Detail
         * @description Full protein detail view with all pockets and stats.
         */
        get: operations["protein_detail_protein__pdb_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protein/{pdb_id}/pockets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Protein Pockets
         * @description Return pocket positions for 3D overlay.
         */
        get: operations["get_protein_pockets_protein__pdb_id__pockets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protein/{pdb_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Protein Structure
         * @description Return the hash-verified prepared structure for one analysis run.
         */
        get: operations["get_protein_structure_protein__pdb_id__structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/figure-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Publication Figure Data
         * @description Keep publication exports disabled until a sealed benchmark exists.
         */
        get: operations["publication_figure_data_publication_figure_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AtlasPocketResponse
         * @description One run-scoped pocket exposed by the Atlas API.
         */
        AtlasPocketResponse: {
            /** Bio Score */
            bio_score: number;
            /** Canonical Eligible */
            canonical_eligible: boolean;
            /** Center */
            center?: [
                number,
                number,
                number
            ] | null;
            /** Depth Score */
            depth_score?: number | null;
            /** Detector Version */
            detector_version: string;
            /** Enclosure Score */
            enclosure_score?: number | null;
            /**
             * Heuristic Quality Tier
             * @enum {string}
             */
            heuristic_quality_tier: "high" | "medium" | "low";
            /** Heuristic Shortlist */
            heuristic_shortlist: boolean;
            /** Hydrophobic Ratio */
            hydrophobic_ratio?: number | null;
            /** Merged Vertices */
            merged_vertices: number;
            /** Pdb Id */
            pdb_id: string;
            /** Pocket Id */
            pocket_id: string;
            /** Prepared Sha256 */
            prepared_sha256: string;
            /** Profile Used */
            profile_used: string;
            /** Rank */
            rank: number;
            /** Run Id */
            run_id: string;
            /** Scoring Contract Version */
            scoring_contract_version: string;
            /** Sphericity */
            sphericity: number;
            /** Validation Status */
            validation_status: string;
            /** Volume */
            volume: number;
            /** Volume Score */
            volume_score?: number | null;
        };
        /** AtlasPocketsResponse */
        AtlasPocketsResponse: {
            /** Available */
            available: boolean;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["AtlasPocketResponse"][];
            /** Limit */
            limit: number;
            /** Message */
            message: string;
            /** Offset */
            offset: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * BatchJobSubmissionResponse
         * @description Response for POST /jobs/batch.
         */
        BatchJobSubmissionResponse: {
            /** Batch Id */
            batch_id: string;
            /** Job Ids */
            job_ids: string[];
            /**
             * Status
             * @default accepted
             */
            status: string;
            /** Total Jobs */
            total_jobs: number;
        };
        /**
         * ErrorEnvelope
         * @description Standard API error envelope.
         */
        ErrorEnvelope: {
            /** Error */
            error: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCancellationResponse */
        JobCancellationResponse: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Job Id */
            job_id: string;
            /** Message */
            message: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobDetailResponse
         * @description Response model for GET /jobs/{job_id}.
         */
        JobDetailResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            error?: components["schemas"]["JobErrorResponse"] | null;
            /** Finished At Utc */
            finished_at_utc?: string | null;
            /** Idempotency Key */
            idempotency_key: string;
            /** Job Id */
            job_id: string;
            request: components["schemas"]["JobSubmitRequest"];
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Started At Utc */
            started_at_utc?: string | null;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobErrorResponse
         * @description Structured job execution failure block.
         */
        JobErrorResponse: {
            /** Attempts */
            attempts: number;
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Message */
            message: string;
        };
        /**
         * JobInput
         * @description User-submitted input payload.
         */
        JobInput: {
            /**
             * Pdb Id
             * @description PDB identifier (e.g. 1CBS).
             */
            pdb_id: string;
        };
        /** JobListItemResponse */
        JobListItemResponse: {
            /** Attempts */
            attempts: number;
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Job Id */
            job_id: string;
            /** Job Type */
            job_type: string;
            /** Pdb Id */
            pdb_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /** JobListResponse */
        JobListResponse: {
            /** Correlation Id */
            correlation_id?: string | null;
            /** Count */
            count: number;
            /** Jobs */
            jobs: components["schemas"]["JobListItemResponse"][];
        };
        /**
         * JobOptions
         * @description Typed options shared by single and batch job submissions.
         */
        JobOptions: {
            /**
             * Assembly Id
             * @default 1
             */
            assembly_id: string | null;
            /** Chains */
            chains?: string[] | null;
            /** Max Retries */
            max_retries?: number | null;
            /**
             * Mode
             * @default static
             * @enum {string}
             */
            mode: "static" | "motion_aware";
            /** N Frames */
            n_frames?: number | null;
            /**
             * Priority
             * @default normal
             * @enum {string}
             */
            priority: "normal" | "high";
            /**
             * Profile
             * @default default
             * @enum {string}
             */
            profile: "default" | "enzyme" | "ppi" | "gpcr";
            /**
             * Representation
             * @default biological_assembly
             * @enum {string}
             */
            representation: "asymmetric_unit" | "biological_assembly" | "predicted_model";
            /**
             * Structure Source
             * @default rcsb
             * @enum {string}
             */
            structure_source: "rcsb" | "alphafold";
            /** Timeout Seconds */
            timeout_seconds?: number | null;
        };
        /**
         * JobStatus
         * @description Supported job lifecycle statuses.
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * JobSubmissionResponse
         * @description Response for POST /jobs.
         */
        JobSubmissionResponse: {
            /**
             * Created At Utc
             * Format: date-time
             */
            created_at_utc: string;
            /** Idempotent Reused */
            idempotent_reused: boolean;
            /** Job Id */
            job_id: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobSubmitRequest
         * @description Create-job request model.
         */
        JobSubmitRequest: {
            input: components["schemas"]["JobInput"];
            /**
             * Job Type
             * @default quick_probe
             * @enum {string}
             */
            job_type: "quick_probe" | "full_analysis";
            options?: components["schemas"]["JobOptions"];
        };
        /** ProteinDetailResponse */
        ProteinDetailResponse: {
            /** Available */
            available: boolean;
            /** Available Runs */
            available_runs: string[];
            /** Avg Bio Score */
            avg_bio_score: number;
            /** Avg Volume */
            avg_volume: number;
            /** Canonical Eligible */
            canonical_eligible: boolean;
            /** Class Distribution */
            class_distribution: {
                [key: string]: number;
            };
            /** Detector Version */
            detector_version: string;
            /** Heuristic Shortlist Pockets */
            heuristic_shortlist_pockets: number;
            /** Max Bio Score */
            max_bio_score: number;
            /** Motion Aware */
            motion_aware?: {
                [key: string]: unknown;
            } | null;
            /** Motion Sampling */
            motion_sampling?: {
                [key: string]: unknown;
            } | null;
            /** Pdb Id */
            pdb_id: string;
            /** Pockets */
            pockets: components["schemas"]["AtlasPocketResponse"][];
            /** Preparation */
            preparation?: {
                [key: string]: unknown;
            } | null;
            /** Prepared Sha256 */
            prepared_sha256: string;
            /** Provenance */
            provenance?: {
                [key: string]: unknown;
            } | null;
            /** Run Id */
            run_id: string;
            /** Scoring */
            scoring?: {
                [key: string]: unknown;
            } | null;
            /** Scoring Contract Version */
            scoring_contract_version: string;
            /** Structure Source */
            structure_source?: {
                [key: string]: unknown;
            } | null;
            /** Total Pockets */
            total_pockets: number;
            /** Validation Status */
            validation_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_artifacts_artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    atlas_overview_atlas_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    atlas_pockets_atlas_pockets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                run_id?: string | null;
                pdb_id?: string | null;
                min_score?: number;
                druggable_only?: boolean;
                druggability_class?: string | null;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtlasPocketsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fpocket_comparison_benchmark_fpocket_comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_known_pockets_benchmark_known_pockets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    export_pockets_csv_export_pockets_csv_get: {
        parameters: {
            query?: {
                pdb_id?: string | null;
                run_id?: string | null;
                min_score?: number;
                heuristic_shortlist_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_job_jobs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSubmissionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_batch_jobs_batch_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchJobSubmissionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCancellationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_job_result_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_visualization_jobs__job_id__visualization_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ops_metrics_ops_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    protein_detail_protein__pdb_id__detail_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                pdb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProteinDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_protein_pockets_protein__pdb_id__pockets_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                pdb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_protein_structure_protein__pdb_id__structure_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                pdb_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publication_figure_data_publication_figure_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
